version: "3"

services:
    mobile:
        image: alex_dwt/mobile-gps-recorder-mobile:latest
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        network_mode: "host"
        privileged: true
        volumes:
            - .:/app